### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by brunocalado** [farling42/fvtt-inline-linktext#2]
Hi! 

Can you provide a noob friendly example? 

Thank you!

**Comment by brunocalado** [comment]
I couldn't make this work.

![image](https://user-images.githubusercontent.com/4999783/187451888-cdf3839d-abd1-42d3-92bf-956a3ef6bfb0.png)

**Comment by farling42** [comment]
Don't include the <> so your link should look like:
```
@inlineJournalEntry[i1UUU...]{Examples}
```

**Comment by brunocalado** [comment]
Nice. Tks.

I would add some noob friendly examples to the readme.

Great module!
