### ISSUE TITLE
Incompatible with systems/modules that override the class of actors, items, etc (e.g. PF2E)

### ISSUE THREAD

**Issue by shemetz** [farling42/fvtt-inline-linktext#3]
When trying to use:

> @inlineActor[mcnoyziJ3Je4nVoU]{test}

I got this bug:

![image](https://user-images.githubusercontent.com/6516621/194744613-7e96e73e-e964-4b35-b217-380b4ee65dc0.png)

![image](https://user-images.githubusercontent.com/6516621/194744617-433d820a-24dd-4cff-913e-e0ae740a8d85.png)

The issue stems from the fact that the pathfinder 2e actor class is CharacterPF2E and not Actor.

I believe this could be solved by refactoring the code, so that instead of converting the doc type to string it explicitly checks classes like this:

`if (doc instanceof Actor) .....`

`if (doc instanceof Item) .....`

Perhaps there is a cleaner way of solving it, though.

**Comment by farling42** [comment]
Thanks for the report!

This is fixed in 0.5.2
